basePath: /api/v1
definitions:
  models.UserLogin:
    properties:
      checkbox:
        type: boolean
      email:
        type: string
      password:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a backend server.
  title: 10tka API
  version: "1.0"
paths:
  /users/login:
    post:
      consumes:
      - application/json
      description: get user by username and password and returns userinfo with cookies
      operationId: get-string-by-int
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.UserLogin'
        "404":
          description: ""
        "500":
          description: ""
      summary: Login
swagger: "2.0"
