basePath: /api/v1
definitions:
  common.Err:
    type: object
  http.Resp:
    properties:
      user:
        $ref: '#/definitions/models.User'
    type: object
  models.User:
    properties:
      about:
        type: string
      email:
        type: string
      id:
        type: string
      name:
        type: string
      patronymic:
        type: string
      phone:
        type: string
      prof_disciplines:
        items:
          type: string
        type: array
      prof_disciplines_str:
        type: string
      role:
        type: string
      student_group:
        type: string
      surname:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a backend server.
  title: 10tka API
  version: "1.0"
paths:
  /users/login:
    post:
      consumes:
      - application/json
      description: get user by username and password and returns userinfo with cookies
      operationId: get-string-by-int
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.Resp'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/common.Err'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.Err'
      summary: Login
  /users/logout:
    post:
      consumes:
      - application/json
      description: clear user's session
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.Err'
      summary: Logout
swagger: "2.0"
